import LocalizedStrings from 'react-native-localization';

export const URL = 'https://cms.goselected.com/';


export let strings = new LocalizedStrings({
    "en-US":{
      Connecting:'Connecting the ',
      Entertainment:'entertainment ',
      World:'world ',
      Register:'Register ',
      Login:'Login ',
      FirstName:'First name ',
      LastName:'Last name',
      Email:'Email ',
      Password:'Password ',
      New_Password:'New password ',
      Do_you_remember:'Do you remember? ',
      Terms1:'I have read and accept the ',
      Terms2:'terms and conditions.',
      Next:'Next ',
      Already_have:'Already have an account? ',
      Welcome:'Welcome to ',
      Forgot:'I forgot my password',
      Reset:'Reset ',
      Guest:'Guest ',
      Talent:'Talent ',
      Agency:'Agency ',
      Done:'Done ',
      Profile_type:'Profile type ',
      Skip:'Skip ',
      DateBirthday:'Date of Birth ',
      Confirm:'Confirm ',
      Cancel:'Cancel ',
      Female:'Female ',
      Male:'Male ',
      Other:'I prefer not to specify',
      Nickname:'Username',
      Register:'Register ',
      AgencyName:'Agency name ',
      EmptyField:'the fields cannot be empty ',
      NewPassword:'New Password ',
      Confirm_password:'Confirm password',
      Confirm_new_password:'Confirm new password ',
      PasswordsNoMatch:'Passwords do not match ',
      BasicInformation:'User information ',
      EditInformation:'Edit user information ',
      SignOut:'Sign Out ',
      Sex:'Sex ',
      MustAcceptTerms:'You must to accept the terms and conditions.',
      SuccesRegister:'Registered Successfully ',
      EmailNotCorrect:'Email is Not Correct ',
      NewPublication:'New Post',
      PublicationText:'Create new publication',
      whatwrire:'Create a...',
      UpdateInformation:'Information updated ',
      Connection_error:'Connection error ',
      In_your_country:'In your country',
      By_production:'By production ',
      AdvancedSearch:'Advanced search ',
      Agencies:'Agencies ',
      All:'All ',
      Friends:'Friends ',
      Write_comment: 'Write a comment',
      Comments:'Comments',
      Locale:'en',
      post:'Text...',
      TitlePub:'Title',
      CreatePost:'Create',
      CastingDetails:'Casting details',
      TalentsRequiered:'Talents required',
      ProyectTitle:'Project title',
      NoCandidates:'The characteristics have not been declared yet',
      ProductionType:'Production type',
      CastingAvailable:'Casting available',
      PaymentRange:'Payment range',
      ShootingDate:'Shooting date',
      CastingRequeriments:'Casting Requeriments',
      ArtistType:'Talent type',
      Age:'Age',
      Location:'Location',
      Skin:'Skin',
      HairSize:'Hair size',
      HairColor:'Hair color',
      EyesColor:'Eyes color',
      Weight:'Weight',
      Height:'Height',
      Payment:'Payment',
      SubmitCasting:'Submit casting',
      Nocomments:'There are no comments',
      Invite:'Invite',
      Contacts:'Contacts',
      Acount:'Account',
      Security:'Security',
      TwoFactor:'Two-factor authentication',
      BlockedUsers:'Blocked users',
      Password:'Password',
      Payments:'Payments',
      PaymentsReference:'Payment references',
      Transactions:'Transactions',
      PaymentRequest:'Payment request',
      Options:'Options',
      SocialNetworks:'Social networks',
      Language:'Language',
      Notifications:'Notifications',
      Support:'Support',
      Help:'Help',
      AccountVerification:'Acount verification',
      NoProjects:'No projects found',
      NewCasting:'New casting',
      NewPost:'New post',
      SavePost:'Save post',
      DeleteSavedPost:'Delete saved post',
      PostSavedSucc:'Post saved in the wishlist',
      PostNoSaved: 'Post deleted from wishlist',
      NoPosts:'No posts',
      Share:'Share',
      WriteReview: 'Write a review',
      Projects:'Projects',
      Experience:'Experience',
      Woman:'Woman',
      Man:'Man',
      View_less:'View less',
      More:'More',
      About:'About',
      Portfolio:'Portfolio',
      OnReview:'On review',
      Posts:'Posts',
      ReportPost:'Report post',
      GoBack:'Go back',
      NoContact:"you don't have any contact",
      NoPortfolio:'you have not added content to your portfolio',
      NoCharacteristics:"You haven't edited your profile characteristics",
      EditProfile:'Edit profile',
      Profile:'Profile',
      SendContactRequest:'Send contact request',
      Friend:'Friend',
      OtherTalentNoCharacteristics:'Talent has not defined its characteristics',
      OtherTalentNoPortfolio:'Talent has not added content to its portfolio',
      OtherAgencyNoPortfolio:'Agency has not added content to its portfolio',
      NoNotifications:'There are no notifications',
      Calendar:'Calendar',
      Representative:'Representative',
      PhoneNumbers:'Phone numbers',
      PostProject:'Post a project',
      PaymentsDue:'Payments due',
      NoPhone:'No phone #',
      Location:'Location',
      CityCountry:'City, country',
      SpecialForYou:'Special for you',
      PostDetail:'Post detail',
      UserCancellPicker:'User cancelled image picker',
      TakePhotoYourCamera:'Take a picture with your camera',
      ChooseFromGallery:'Choose an image from your gallery',
      FriendRequest:'Friend request sent',
      Accept:'Accept',
      Decline:'Decline',
      Cancel:'Cancel',
      FriendRequestCanceled:'Friend Request Canceled',
      FriendRequestAccepted:'Friend Request Accepted',
      Removefriends:'Remove from my friends',
      FriendRemoved:'Friend removed',
      Report:'Report',
      ReasonReport:'Reason for the report',
      hour:'hour',
      day:'day',
      month:'month',
      year:'year',
      hours:'hours',
      days:'days',
      months:'months',
      years:'years',
      RequieredTitle:'Required publication title field',
      RequieredThinking:'Field "What are you thinking?" required',
      AddPhoto:'Add photo',
      HairType:'Hair type',
      NoWishlist:'You have no posts saved in your wishlist',
      UpdateProfile:'Update profile',
      Talents:'Talents',
      Project:'Project',
      Messages:'Messages',
      ReportUser:'Report user',
      ReportProject:'Report project',
      EnterNewPassword:'Enter your new password',
      ResetPassword:'Reset Password',
      Finish:'Finish',
      quantity:'Quantity',
      Minweight:'Minimum weight',
      Maxweight:'Maximum weight',
      Minheight:'Minimum height',
      Maxheight:'Maximum height',
      Minimumage:'Minimum age',
      Maximumage:'Maximum age',
      Budget:'Budget',
      City:'City',
      Add:'Add',
      UpdatePassword:'Update password',
      OldPassword:'Old password',
      EnterPasswordAgain:'Repeat new password',
      ReasonVerification:'Reason for verification',
      VerificationRequestSent:'Verification request sent',
      VerifiedAcount:'Verified account',
      PasswordUpdated: 'Password updated',
      ActiveTwoFactors:'Enable two-factor authentication',
      CodeEmaiLogin:'A verification code will be sent to your email when you log in',
      AuthenticationEnabled:'Authentication enabled',
      AuthenticationDisabled:'Authentication disabled',
      Send:'Send',
      HowCanWeHelp:'How can we help you?',
      HelpRequestSent:'Help request sent',
      AuthenticationCode:'Authentication code',
      amount:'Amount',
      Available:'Available',
      MoneyHold:'Money on hold',
      AuthorizedAmount:'Authorized amount',
      PastTransactions:'Past transactions',
      NoTransactions:'You have no past transactions',
      AddDeleteEdit:'Add, delete or edit your payment references',
      NoReferences:'You have not added any payment references',
      ReferenceType:'Reference type',
      Card:'Card',
      InterbankAccount:'Interbank account',
      PayPal:'PayPal',
      CardType:'Card type',
      Debit:'Debit',
      Credit:'Credit',
      ReferenceNumber:'Reference number',
      Bank:'Bank',
      AddPaymentReference:'Add payment reference',
      EditPaymentReference:'Edit payment reference',
      DeletePaymentReference:'Delete payment reference',
      PaymentReferenceAddedSuccessfully:'Payment reference added successfully',
      PaymentReferenceDeletedSuccessfully:'Payment reference deleted successfully',
      PaymentReferenceUpdatedSuccessfully:'Payment reference updated successfully',
      SpanishLanguage:'Spanish',
      EnglishLanguage:'English',
      AvailableLanguages:'Available languages',
      Contract:'Contract',
      RequestPayment:'Request payment',
      Birthays:'Birthays',
      Added:'Added',
      Accepted:'Accepted',
      Tagged:'Tagged',
      Comment:'Comment',
      Promotions:'Promotions',
      Postulate:'Postulado',
      ConfigNotifications:'Configure notifications',
      UpdatedConfiguration:'Updated configuration',
      SelectSkinTone:'Select the color tone of your skin',
      SelectEyeColor:'Select the color of your eyes',
      SelectHairColor:'Select the color of your hair',
      SelectSizeHair:'Select the size of your hair',
      SelectMeasureHeight:'Select unit of measure of height',
      SelectMeasureWeight:'Select unit of measure of weight',
      UpdateProyect:'Update Project',
      Update:'Update',
      Measure:'Measure',
      MoreInformation:'More information',
      LessInformation:'LessInformation',
      Back:'Back',
      ProductionDetails:'Production Details',
      Dates:'Date',
      CastingAvailibility:'Casting Availability',
      AditionalComments:'Aditional comments',
      Commission:'Commission',
      Budget:'Budget',
      TotalPay:'Total Pay',
      Paidout:'Paid out',
      Subtracting:'Subtracting',
      MensajePaypal:'Are you sure you want to pay',
      Payments:'Payments',
      Accept:'Accept',
      ContractDescription:'Contract Description',
      AddDeleteEditPhone:'Add, delete or edit your phone numbers',
      AddPhoneNumber:'Add phone number',
      EditPhoneNumber:'Edit phone number',
      DeletePhoneNumber:'Delete phone number',
      PhoneNumber:'Phone number',
      TelephoneNumberAdded:'Telephone number added',
      TelephoneNumberUpdated:'Telephone number updated',
      PhoneNumberDeleted:'Phone number deleted',
      ProductionDetails:'Production Details',
      Dates:'Date',
      CastingAvailibility:'Casting Availability',
      addrequired:'Add required talent',
      Commission:'Commission',
      Budget:'Budget',
      TotalPay:'Total Pay',
      Paidout:'Paid out',
      Subtracting:'Subtracting',
      MensajePaypal:'Are you sure you want to pay',
      Payments:'Payments',
      Deposits:'Deposits',
      Accept:'Accept',
      SendContract:'Send Contract',
      ContractDescription:'Contract Description',
      PaymentRequestSended:'Payment request sended',
      TypeMessage:'Type a Message',
      Contract:'Contract',
      Toaccept:'To accept',
      Torefuse:'To refuse',
      answerpaymentrequest:'Answer payment request',
      to:'to',
      StartDate:'Start date',
      EndDate:'End date',
      Search:'Search',
      SearchAndCastRequest:'Make a request',
      ChooseYourProject:'Choose your project',
      ChooseYourScreen:'Choose your screen',
      ChooseDates:'Choose the dates of your request',
      SendSearchAndCastRequest:'Send search and cast request',
      SearchAndCastRequestSended:'Search and cast request sended:',
      EditPortfolio:'Edit portfolio',
      project:'Project',
      SearchContact:'Search Contact',
      SearchContactContract:'Search Contact Contract',
      AcceptContract:'Accept Contract',
      RejectContract:'Reject Contract',
      DeleteImage:'Delete image',
      DeleteVideo:'Delete video',
      ItemDeletedSuccessfully:'Item deleted successfully',
      AddImagePortfolio:'Add image to portfolio',
      Title:'Title',
      ImageAdded:'Image added',
      AddVideoPortfolio:'Add video to portfolio',
      VideoAdded:'Video added',
      NoLinkYoutube:'YouTube link is not correct',
      YoutubeLink:'Youtube link',
      AcceptTermsCondition:'Accept Terms and Conditions',
      MensajeRegistroDetalle:'Select one of the options',
      MessajeRegistro:'Registry',
      Aspirants:'Aspirants',
      ListProjects:'List of Projects',
      NoCity:'Undefined city',
      Description:'Description',
      Name:'Name',
      AddTalents:'Add Talents',
      Less1mb:'The image must be less than 1MB',
      MandatoryContractField:'Mandatory Contract Field',
      MandatoryTitleField:'Mandatory title field',
      MandatoryDescriptionField:'Mandatory description field',
      MandatoryInitialDateField:'Mandatory initial date field',
      MandatoryEndDateField:'Mandatory end date field',
      MandatoryUbicationField:'Mandatory ubication field',
      MandatoryImageField:'Mandatory image field',
      AmountLessThanCeroEmpty:'Amount cannot be less than 0 or empty',
      AmountMustLessRemaining:'The amount to be paid must be less than the remaining',
      Search:'Search',
      NoSearch:'No searches found',
      ReasonVerificationExample:'Why should we verify you? (example: send press releases published by important means)',
      AddOfficialIdentification:'add official identification',
      OfficialIdentificationTalentExample:"The identification must be official issued by the government (driver's licenses, residences, passports);",
      OfficialIdentificationAgencyExample:"The identification must be official issued by the government (company registration, certificate of origin along with the representative's data);",
      avisoprivacidad:'Notice of Privacy',
      PhoneNumberInvalid:'This phone number is invalid',
      CastNow:'Cast now',
      Wishlist:'Wish list',
      ProjectOptions:'Project options',
      Home:'Home',
      SearchAndCast:'Search and cast',
      Example:'Example: Include kissing scenes, no tattoos, no piercing',
      ProjectCreated:'Your project has been created, now you can: update project or add talent',
      Request:'Request',
      ValidateDate:'The date of birth must be over 18 years old',
      ViewAll:'View all',
      NotFoundCity:'Not found cities',
      SearchCity:'Search a city',
      Sort:'Sort',
      NoPhoto:'Without picture',
      Gender:'Gender',
      Undefined:'Undefined',
      SelectTypeHair:'Select type hair',
      NoProjectsToday:"you don't have any project for this day",
      NoSearchContactResult:'The search did not return any results with that name',
      See:'See',
      Free:'Free',
      FacebookLink:'Facebook link',
      TwitterLink:'Twitter link',
      NoApply:'You do not apply for the project',
      Phone:'Teléfono',
      Delete:'Delete',
      PostRemoved:'Post removed',
      FreeDate:'Free date',
      AddTalent:'Add Talent',
      IsItAnFreeTalentType:'Can anyone apply?',
      Yes:'Yes',
      No:'No',
      EveryoneCanApply:'Everyone can apply',
      WantToSpecifyWhatNeed:'I want to specify the talent I need',
      whatToDo:'WHAT TO DO?',
      DescriptionCharacter:'Description of the character, idea or necessary information that the talent must know',
      TalentsMustAttach:'TALENTS MUST ATTACH',
      Photo:'Photo',
      PDFWithInformation:'PDF WITH INFORMATION, SCENE, ETC.',
      AttachPDF:'Attach a PDF',
      Save:'Save',
      Publish:'Publish',
      Published:'Published',
      Parameters:'PARAMETERS',
      Features:'FEATURES',
      YourCastingSucces:'Your casting has been published successfully',
      LinkVideo:'Link video',
      WebPageLink:'Web page link',
      Screen1:'Screen 1',
      Screen2:'Screen 2',
      Screen3:'Screen 3',
      ChooseAnOption:'Choose an option',
      NoItemFound:'No item found',
      ChangePdf:'Change PDF',
      NoAspirants:'No candidate has been applied for',
      SeePDF:'See PDF',
      AreYoulogout:'Are you sure you want to log out?',
      Minutes:'minutes',
      JustNow:'Just now',
      Address:'Address',
      CastingSuccessfully:'Casting successfully',
      Contact:'Contact',
      UploadCV:'Upload CV',
      NoPaymentRequests:'No payment requests',
      NameLastNameRepresentative:'Name and last name of the legal representative',
      ImageRequired:'Image required',
      You:'You',
      SelectTags:'Select tags',
      NoMatter: 'No matter',
      SeeDetails:'See details',
      Congratulations:'Congratulations',
      YouHaveBeenSelected:'You have been selected for the production of',
      Of:'of',
      AddVideo:'Add video',
      TalentAccepted:'Talent accepted correctly',
      ReplacePDF:'Replace PDF',
      RemovePDF:'Remove PDF',
      DeleteChat:'Are you sure to delete the chat with this user?',
      Users:'Users',
      User:'User',
      TaggedUsers:'Tagged users',
      CreateCount:'Create account',
      NameLastName:'Name and last name',
      JoinAnd:'Join and ',
      Connect:'connect ',
      WithGlobalEntertainment:'with global entertainment',
      Hello:'Hello!',
      Wallet:'Wallet',
      Movements:'Movements',
      TermsConditionsPrivacyNotice:'Terms, Conditions and Privacy Notice',
      ThankSharingSelected:'Thanks for sharing selected!',
      ShareWithFriend:'Share with a friend',
      SelectedNeeds:'Selected needs',
      CameraPermission:'Camera permission',
      MicrophonePermission:'Microphone permission',
      Grant:'Grant',
      From:'From',
      Shared:'Shared',
      Weeks:'w',
      Reported:'Reported',
      TopToTag:'Tap to tag',
      DevelopmentProgress:'Development in progres',
      InformationSaved:'Information saved',
      SocialNetworkNotAdded:'Social network not added',
      LoadingChat:'Loading chat...'
    },
    es:{
      Connecting:'Conectando el ',
      Entertainment:'entretenimiento ',
      World:'global ',
      Register:'Registrar ',
      Login:'Inicia sesión ',
      FirstName:'Nombre ',
      LastName:'Apellidos',
      Email:'Correo electrónico ',
      Password:'Contraseña ',
      New_Password:'Nueva contraseña ',
      Do_you_remember:'¿Recuerdas tu contraseña? ',
      Terms1:'He leído y acepto los ',
      Terms2:'términos y condiciones.',
      Next:'Siguiente ',
      Already_have:'¿Ya tienes una cuenta? ',
      Welcome:'Bienvenido a ',
      Forgot:'Olvidé mi contraseña',
      Reset:'Restablecer ',
      Guest:'Invitado ',
      Talent:'Talento ',
      Agency:'Agencia ',
      Done:'Hecho ',
      Profile_type:'Tipo de usuario ',
      Skip:'Omitir ',
      DateBirthday:'Fecha de nacimiento ',
      Confirm:'Confirmar ',
      Cancel:'Cancelar ',
      Female:'Femenino ',
      Male:'Masculino ',
      Other:'Prefiero no especificar',
      Nickname:'Nombre de usuario ',
      Register:'Registrar ',
      AgencyName:'Nombre de agencia ',
      EmptyField:'Los campos no pueden quedar vacíos ',
      NewPassword:'Nueva contraseña ',
      Confirm_password:'Confirmar contraseña ',
      Confirm_new_password:'Confirmar nueva contraseña ',
      PasswordsNoMatch:'Las contraseñas no coinciden ',
      BasicInformation:'Información de usuario',
      EditInformation:'Editar información de usuario ',
      SignOut:'Cerrar Sesión ',
      Sex:'Sexo ',
      MustAcceptTerms:'Debes aceptar los términos y condiciones.',
      SuccesRegister:'Registrado correctamente ',
      EmailNotCorrect:'El email no es correcto ',
      NewPublication:'Nueva Publicación',
      whatwrire:'¿Que quieres escribir? ',
      UpdateInformation:'Información actualizada ',
      Connection_error:'Error de conexión ',
      In_your_country:'En tu país',
      By_production:'Por producción ',
      AdvancedSearch:'Búsqueda avanzada',
      Agencies:'Agencias ',
      All:'Todo ',
      Friends:'Amigos ',
      Write_comment: 'Escribe un comentario',
      Comments:'Comentarios',
      Locale:'es',
      post:'Empieza a escribir...',
      TitlePub:'Titulo',
      CreatePost:'Crear',
      CastingDetails:'Detalles de casting',
      TalentsRequiered:'Talentos requeridos',
      ProyectTitle:'Titulo del proyecto',
      NoCandidates:'No se han declarado las características',
      ProductionType:'Tipo de producción',
      CastingAvailable:'Disponibilidad de casting',
      PaymentRange:'Rango de pago',
      ShootingDate:'Fecha de rodaje',
      CastingRequeriments:'Requerimientos de casting',
      ArtistType:'Tipo de talento',
      Age:'Edad',
      Location:'Locación',
      Skin:'Piel',
      HairSize:'Tamaño de cabello',
      HairColor:'Color de cabello',
      EyesColor:'Color de ojos',
      Weight:'Peso',
      Height:'Altura',
      Payment:'Pago',
      SubmitCasting:'Aplicar a casting',
      Nocomments:'No existen comentarios',
      Invite:'Invitar',
      Contacts:'Contactos',
      Acount:'Cuenta',
      Security:'Seguridad',
      TwoFactor:'Autenticación de dos factores',
      BlockedUsers:'Usuarios bloqueados',
      Password:'Contraseña',
      Payments:'Pagos',
      Deposits:'Depósitos',
      PaymentsReference:'Referencias de pago',
      Transactions:'Transacciones',
      PaymentRequest:'Solicitud de pago',
      Options:'Opciones',
      SocialNetworks:'Redes sociales',
      Language:'Idioma',
      Notifications:'Notificaciones',
      Support:'Soporte',
      Help:'Ayuda',
      AccountVerification:'Verificación de cuenta',
      NoProjects:'No se encontraron proyectos',
      NewCasting:'Nuevo casting',
      NewPost:'Nuevo post',
      SavePost:'Guardar publicación',
      DeleteSavedPost:'Eliminar publicación guardada',
      PostSavedSucc:'Publicación guardada en tu lista de deseos',
      PostNoSaved:'Publicación eliminada de tu lista de deseos',
      NoPosts:'Sin publicaciones',
      Share:'Compartir',
      WriteReview:'Escribe una opinión',
      Projects:'Proyectos',
      Experience:'Experiencia',
      Woman:'Mujer',
      Man:'Hombre',
      View_less:'Ver menos',
      More:'Más',
      About:'Acerca de',
      Portfolio:'Portafolio',
      OnReview:'Postulado',
      Posts:'Publicaciones',
      ReportPost: 'Reportar publicación',
      GoBack:'Volver',
      NoContact:"No tienes ningún contacto",
      NoPortfolio:'No has añadido contenido a tu portafolio',
      NoCharacteristics:"No has editado las características de tu perfil",
      EditProfile:'Editar Perfil',
      Profile:'Perfil',
      SendContactRequest:'Enviar solicitud de contacto',
      Friend:'Amigo',
      OtherTalentNoCharacteristics:'El talento no ha definido sus características',
      OtherTalentNoPortfolio:'El talento no ha añadido contenido a su portafolio',
      OtherAgencyNoPortfolio:'La agencia no ha añadido contenido a su portafolio',
      NoNotifications:'No hay notificaciones',
      Calendar:'Calendario',
      Representative:'Representante',
      PhoneNumbers:'Números telefónicos',
      PostProject:'Publica un proyecto',
      PaymentsDue:'Pagos adeudados',
      NoPhone:'Sin teléfono #',
      Location:'Ubicación',
      CityCountry:'Ciudad, país',
      SpecialForYou:'Especial para ti',
      PostDetail:'Detalles de publicación',
      UserCancellPicker:'El usuario canceló la selección de imagen',
      TakePhotoYourCamera:'Toma una fotografía con tu cámara',
      ChooseFromGallery:'Elige una imagen de tu galería',
      FriendRequest:'Solicitud de amistad enviada',
      Accept:'Aceptar',
      Decline:'Rechazar',
      Cancel:'Cancelar',
      FriendRequestCanceled:'Solicitud de amigo cancelada',
      FriendRequestAccepted:'Solicitud de amigo aceptada',
      Removefriends:'Eliminar de mis amigos',
      FriendRemoved:'Amigo eliminado',
      Report:'Reportar',
      ReasonReport:'Motivo de reporte',
      hour:'hora',
      day:'día',
      month:'mes',
      year:'año',
      hours:'horas',
      days:'días',
      months:'meses',
      years:'años',
      RequieredTitle:'Campo titulo publicación obligatorio',
      RequieredThinking: 'Campo "¿Qué estás pensando?" obligatorio',
      AddPhoto:'Añadir foto',
      HairType:'Tipo de cabello',
      NoWishlist:'No tienes publicaciones guardadas en tu lista de deseos',
      UpdateProfile:'Actualizar perfil',
      Talents:'Talentos',
      Project:'Proyecto',
      Messages:'Mensajes',
      ReportUser:'Reportar usuario',
      ReportProject:'Reportar proyecto',
      EnterNewPassword:'Introduce tu nueva Contraseña',
      ResetPassword:'Contraseña reestablecida',
      Finish:'Finalizar',
      quantity:'Cantidad',
      Minweight:'Peso Mínimo',
      Maxweight:'Peso Máximo',
      Minheight:'Altura Mínimo',
      Maxheight:'Altura Máximo',
      Minimumage:'Edad Mínima',
      Maximumage:'Edad Máxima',
      Budget:'Presupuestó',
      City:'Ciudad',
      Add:'Agregar',
      UpdatePassword:'Actualizar contraseña',
      OldPassword:'Contraseña anterior',
      EnterPasswordAgain:'Repetir nueva contraseña',
      ReasonVerification:'Razón de la verificación',
      VerificationRequestSent:'Solicitud de verificación enviada',
      VerifiedAcount:'Cuenta verificada',
      PasswordUpdated:'Contraseña actualizada',
      ActiveTwoFactors:'Activar autenticación de dos factores',
      CodeEmaiLogin:'Se enviará un código de verificación a su correo cuando inicie sesión',
      AuthenticationEnabled:'Autentificación activada',
      AuthenticationDisabled:'Autentificación desactivada',
      Send:'Enviar',
      HowCanWeHelp:'¿Cómo te podemos ayudar?',
      HelpRequestSent:'Solicitud de ayuda enviada',
      AuthenticationCode:'Código de autenticación',
      amount:'Monto',
      Available:'Disponible',
      MoneyHold:'Dinero en espera',
      AuthorizedAmount:'Monto autorizado',
      PastTransactions:'Transacciones pasadas',
      NoTransactions:'No tienes transacciones pasadas',
      AddDeleteEdit:'Añade, elimina o edita tus referencias de pago',
      NoReferences:'No has añadido ninguna referencia de pago',
      ReferenceType:'Tipo de referencia',
      Card:'Tarjeta',
      InterbankAccount:'Cuenta interbancaria',
      PayPal:'PayPal',
      CardType:'Tipo de tarjeta',
      Debit:'Débito',
      Credit:'Crédito',
      ReferenceNumber:'Número de referencia',
      Bank:'Banco',
      AddPaymentReference:'Añadir referencia de pago',
      EditPaymentReference:'Editar referencia de pago',
      DeletePaymentReference:'Eliminar referencia de pago',
      PaymentReferenceAddedSuccessfully: 'Referencia de pago añadida correctamente',
      PaymentReferenceDeletedSuccessfully:'Referencia de pago eliminada correctamente',
      PaymentReferenceUpdatedSuccessfully:'Referencia de pago actualizada correctamente',
      SpanishLanguage:'Español',
      EnglishLanguage:'Inglés',
      AvailableLanguages:'Idiomas disponibles',
      Contract:'Contrato',
      RequestPayment:'Solicitar pago',
      Birthays:'Cumpleaños',
      Added:'Añadido(a)',
      Accepted:'Aceptado(a)',
      Tagged:'Etiqueta',
      Comment:'Comentario',
      Promotions:'Promociones',
      Postulate:'Postulado',
      ConfigNotifications:'Configurar notificaciones',
      UpdatedConfiguration:'Configuración actualizada',
      SelectSkinTone:'Selecciona el tono de color de tu piel',
      SelectEyeColor:'Selecciona el color de tus ojos',
      SelectHairColor:'Selecciona el color de tu cabello',
      SelectSizeHair:'Selecciona el tamaño de tu cabello',
      SelectMeasureHeight:'Selecciona unidad de medida de altura',
      SelectMeasureWeight:'Selecciona unidad de medida de peso',
      UpdateProyect:'Actualizar Proyecto',
      Update:'Actualizar',
      Measure:'Medida',
      MoreInformation:'Más información',
      LessInformation:'Menos información',
      Back:'Atrás',
      ProductionDetails:'Detalles de producción',
      Dates:'Fecha',
      CastingAvailibility:'Disponibilidad de función',
      Commission:'Comisión',
      Budget:'Presupuesto',
      TotalPay:'Total Pagar',
      Paidout:'Pagado',
      Subtracting:'Restante',
      MensajePaypal:'Esta seguro que desea pagar',
      Payments:'Pagos',
      Accept:'Aceptar',
      SendContract:'Enviar Contrato',
      ContractDescription:'Descripción Contrato',
      AddDeleteEditPhone:'Añade, elimina o edita tus números telefónicos',
      AddPhoneNumber:'Añadir número telefónico',
      EditPhoneNumber:'Editar número telefónico',
      DeletePhoneNumber:'Eliminar número telefónico',
      PhoneNumber:'Número telefónico',
      TelephoneNumberAdded:'Número telefónico añadido',
      TelephoneNumberUpdated:'Número telefónico actualizado',
      PhoneNumberDeleted:'Número telefónico eliminado',
      ProductionDetails:'Detalles de producción',
      Dates:'Fecha',
      CastingAvailibility:'Disponibilidad de función',
      AditionalComments:'Comentarios adicionales',
      addrequired:'Agregar talento requerido',
      Commission:'Comisión',
      Budget:'Presupuesto',
      TotalPay:'Total Pagar',
      Paidout:'Pagado',
      Subtracting:'Restante',
      MensajePaypal:'Esta seguro que desea pagar',
      Payments:'Pagos',
      Accept:'Aceptar',
      ContractDescription:'Descripcion Contrato',
      PaymentRequestSended:'Solicitud de pago enviada',
      TypeMessage:'Escribe un mensaje',
      Contract:'Contrato',
      Toaccept:'Aceptar',
      Torefuse:'Rechazar',
      answerpaymentrequest:'Responder solicitud de pagos',
      to:'a',
      StartDate:'Fecha de inicio',
      EndDate:'Fecha de fin',
      Search:'Buscar',
      SearchAndCastRequest:'Hacer una solicitud',
      ChooseYourProject:'Elige tu proyecto',
      ChooseYourScreen:'Elige tu pantalla',
      ChooseDates:'Elige las fechas de tu solicitud',
      SendSearchAndCastRequest:'Enviar solicitud de search and cast',
      SearchAndCastRequestSended:'Solicitud de search and cast enviada',
      EditPortfolio:'Editar portafolio',
      project:'Proyecto',
      SearchContact:'Buscar Contactos',
      SearchContactContract:'Buscar Contactos Contrato',
      PublicationText:'Crear nueva publicación',
      AcceptContract:'Aceptar Contrato',
      RejectContract:'Rechazar Contrato',
      DeleteImage:'Eliminar imagen',
      DeleteVideo:'Eliminar Video',
      ItemDeletedSuccessfully:'Elemento eliminado correctamente',
      AddImagePortfolio:'Añadir imagen al portafolio',
      Title:'Titulo',
      ImageAdded:'Imagen añadida',
      AddVideoPortfolio:'Añadir video al portafolio',
      VideoAdded:'Video añadido',
      YoutubeLink:'Enlace de youtube',
      NoLinkYoutube:'El enlace de youtube no es correcto',
      AcceptTermsCondition:'Aceptar término y condiciones',
      MessajeRegistro:'Registro',
      MensajeRegistroDetalle:'Seleccione una de las opciones',
      Aspirants:'Postulados',
      ListProjects:'Listado de Proyectos',
      NoCity:'Ciudad sin definir',
      Description:'Descripción',
      Name:'Nombre',
      AddTalents:'Agregar Talentos',
      Less1mb:'La imagen debe ser menor a 1MB',
      MandatoryContractField:'Campo de contrato obligatorio',
      MandatoryTitleField:'Campo de título obligatorio',
      MandatoryDescriptionField:'Campo de descripción obligatorio',
      MandatoryInitialDateField:'Campo de fecha de inicio obligatorio',
      MandatoryEndDateField:'Campo de fecha de fin obligatorio',
      MandatoryUbicationField:'Campo de ubicación obligatorio',
      MandatoryImageField:'Campo de imagen obligatorio',
      AmountLessThanCeroEmpty:'Monto no puede ser menor a 0 ó vacío',
      AmountMustLessRemaining:'El monto a pagar debe ser menor al restante',
      Search:'Buscar',
      NoSearch:'No se encontraron búsquedas',
      ReasonVerificationExample:'¿Porque te debemos verificar? (ejemplo:enviar notas de prensa publicadas por medios importantes) ',
      AddOfficialIdentification:'Añadir identificación oficial',
      OfficialIdentificationTalentExample:"La identificación debe ser oficial emitida por el gobierno (Licencias de conducir, residencias, pasaportes);",
      OfficialIdentificationAgencyExample:"La identificación debe ser oficial emitida por el gobierno (registro de empresa, certificado de origen junto con los datos del representante);",
      avisoprivacidad:'Aviso de Privacidad',
      PhoneNumberInvalid:'Este número de teléfono no es válido',
      CastNow:'Postúlate',
      Wishlist:'Lista de deseos',
      ProjectOptions:'Opciones de proyecto',
      Home:'Inicio',
      SearchAndCast:'Buscar y postularse',
      Example:'Ejemplo: Incluye escenas de beso, no tatuajes, no perforaciones',
      ProjectCreated:'Se ha creado tu proyecto, ahora bien puedes: actualizar proyecto ó añadir talento',
      Request:'Solicitud',
      ValidateDate:'La fecha de nacimiento debe ser mayor a 18 años',
      ViewAll:'Ver todo',
      NotFoundCity:'Ciudades no encontradas',
      SearchCity:'Busca una ciudad',
      Sort:'Ordenar',
      NoPhoto:'Sin imagen',
      Gender:'Género',
      Undefined:'Sin definir',
      SelectTypeHair:'Selecciona tipo de cabello',
      NoProjectsToday:'No tienes ningún proyecto para este día',
      NoSearchContactResult:'La búsqueda no arrojó ningún resultado con ese nombre',
      See:'Ver',
      Free:'Libre',
      FacebookLink:'Enlace de facebook',
      TwitterLink:'Enlace de twitter',
      NoApply:'No aplicas para el proyecto',
      Phone:'Teléfono',
      Delete:'Eliminar',
      PostRemoved:'Publicación eliminada',
      FreeDate:'Fecha libre',
      AddTalent:'Agregar Talento',
      IsItAnFreeTalentType:'¿Cualquiera puede postularse?',
      Yes:'Si',
      No:'No',
      EveryoneCanApply:'Cualquiera puede postularse',
      WantToSpecifyWhatNeed:'Quiero específicar el talento que necesito',
      whatToDo:'¿QUÉ HACER?',
      DescriptionCharacter:'Descripción del personaje, idea o información necesaria que el talento debe conocer',
      TalentsMustAttach:'LOS TALENTOS DEBEN ADJUNTAR',
      Photo:'Fotografía',
      PDFWithInformation:'PDF con información, escena, etc.',
      AttachPDF:'Adjunta un PDF',
      Save:'Guardar',
      Publish:'Publicar',
      Published:'Publicado',
      Parameters:'PARÁMETROS',
      Features:'CARACTERÍSTICAS',
      YourCastingSucces:'Tu casting se ha publicado con éxito',
      LinkVideo:'Enlace de vídeo',
      WebPageLink:'Enlace de página web',
      Screen1:'Pantalla 1',
      Screen2:'Pantalla 2',
      Screen3:'Pantalla 3',
      ChooseAnOption:'Elige una opción',
      NoItemFound:'No se encontró ningún elemento',
      ChangePdf:'Cambiar PDF',
      NoAspirants:'No se ha postulado ningún aspirante',
      SeePDF:'Ver PDF',
      AreYoulogout:'¿Está seguro(a) que desea cerrar sesión?',
      Minutes:'minutos',
      JustNow:'Hace un momento',
      Address:'Dirección',
      CastingSuccessfully:'Casting exitoso',
      Contact:'Contacto',
      UploadCV:'Cargar CV',
      NoPaymentRequests:'No hay solicitudes de pago',
      NameLastNameRepresentative:'Nombre y apellido del representante legal',
      ImageRequired:'Se requiere imagen',
      You:'Tú',
      SelectTags:'Selecciona etiquetas',
      NoMatter:'No importa',
      SeeDetails:'Ver detalles',
      Congratulations:'Felicidades',
      YouHaveBeenSelected:'Haz sido seleccionado(a) para la producción de',
      Of:'de',
      AddVideo:'Añadir video',
      TalentAccepted:'Talento aceptado correctamente',
      ReplacePDF:'Remplazar PDF',
      RemovePDF:'Eliminar PDF',
      DeleteChat:'¿Estás seguro borrar el chat con este usuario?',
      Users:'Usuarios',
      User:'Usuario',
      TaggedUsers:'Usuarios etiquetados',
      CreateCount:'Crear cuenta',
      NameLastName:'Nombre y apellido',
      JoinAnd:'Únete y ',
      Connect:'conecta ',
      WithGlobalEntertainment:'con el entretenimiento global',
      Hello:'Hola!',
      Wallet:'Cartera',
      Movements:'Movimientos',
      TermsConditionsPrivacyNotice:'Términos, condiciones y Aviso de privacidad',
      ThankSharingSelected:'¡Gracias por compartir selected!',
      ShareWithFriend:'Compartir con un amigo',
      SelectedNeeds:'Selected necesita',
      CameraPermission:'Permiso para el uso de la cámara',
      MicrophonePermission:'Permiso para el uso del micrófono',
      Grant:'Conceder',
      From:'De',
      Shared:'Compartido',
      Weeks:'sem',
      Reported:'Reportado',
      TopToTag:'Toca para etiquetar',
      DevelopmentProgress:'Desarrollo en progreso',
      InformationSaved:'Información guardada',
      SocialNetworkNotAdded:'Red social no añadida',
      LoadingChat:'Cargando chat...'
    }
   });
